select * from tbpostransact where promid='18' order by recdate 
select DISTINCT promid from tbpostransact where promid is not null order by promid

select * from tbpostransactsum where promid='18'

-------01----------
 select * from tbpostransactsum where loca='02' and descrip like 'PROM#%'
 and zno='1' and unitno='1'

 update tbpostransactsum set promid='1' where loca='02' and descrip like 'PROM#%'
 and zno='1' and unitno='1'

 ------04-------------------
select * from tbpostransactsum AS PS JOIN LOCA02.DBO.TBPOSTRANSACT AS P ON PS.ITEMCODE=P.ITEMCODE
AND PS.REFCODE=P.REFCODE AND PS.DESCRIP=P.DESCRIP AND PS.IDI1=P.IDI1 AND PS.IDISCOUNT1=P.IDISCOUNT1
AND PS.IDX=P.IDX
WHERE P.PROMID='4' ORDER BY P.IDX

BEGIN TRAN
UPDATE PS SET PS.PROMID=P.PROMID FROM LOCA02.DBO.TBPOSTRANSACT AS P JOIN tbpostransactsum AS PS
ON P.ITEMCODE=PS.ITEMCODE AND P.REFCODE=PS.REFCODE AND P.DESCRIP=PS.DESCRIP AND P.IDI1=PS.IDI1 AND P.IDISCOUNT1=PS.IDISCOUNT1
AND P.IDX=PS.IDX
WHERE P.PROMID='4'
COMMIT
ROLLBACK

 ------05,06,07,08,-------------------
select * from tbpostransactsum AS PS JOIN LOCA02.DBO.TBPOSTRANSACT AS P ON PS.ITEMCODE=P.ITEMCODE
AND PS.REFCODE=P.REFCODE AND PS.DESCRIP=P.DESCRIP AND PS.IDI1=P.IDI1 AND PS.IDISCOUNT1=P.IDISCOUNT1
AND PS.IDX=P.IDX and P.LOCA=PS.LOCA
WHERE P.PROMID='9' ORDER BY P.IDX

BEGIN TRAN
UPDATE PS SET PS.PROMID=P.PROMID FROM LOCA02.DBO.TBPOSTRANSACT AS P JOIN tbpostransactsum AS PS
ON P.ITEMCODE=PS.ITEMCODE AND P.REFCODE=PS.REFCODE AND P.DESCRIP=PS.DESCRIP AND P.IDI1=PS.IDI1 AND P.IDISCOUNT1=PS.IDISCOUNT1
AND P.IDX=PS.IDX and P.LOCA=PS.LOCA
WHERE P.PROMID='8'
COMMIT
ROLLBACK

 ------09,10,13,14,15,16,17,18,19,20,21,22,23,24,28,33,34,35,37,40,41,45,46-------------------
 select * from tbpostransactSUM where loca='02' and promid IS NULL

select * from LOCA05.DBO.TBPOSTRANSACT where loca='02' and promid='20' AND ITEMCODE NOT IN (
select PS.ItemCode from tbpostransactsum AS PS JOIN LOCA05.DBO.TBPOSTRANSACT AS P ON PS.ITEMCODE=P.ITEMCODE
AND PS.REFCODE=P.REFCODE AND PS.DESCRIP=P.DESCRIP AND PS.IDI1=P.IDI1 AND PS.IDISCOUNT1=P.IDISCOUNT1 
AND P.IDIS1=PS.IDIS1 AND P.LOCA=PS.LOCA AND P.ZNO=PS.ZNO 
AND P.RECEIPT=PS.RECEIPT 
AND P.ROWNO=PS.ROWNO
WHERE P.PROMID='23')

SELECT * FROM tbPostransactSum WHERE ItemCode='20010007' AND LOCA='02' AND DESCRIP LIKE 'prom%' AND RefCode='20010007#ASH\XL'
UPDATE tbPostransactSum SET PROMID='20'
WHERE ItemCode='20010007' AND LOCA='02' AND DESCRIP LIKE 'prom%' AND RefCode='20010007#ASH\XL'

select * from tbpostransactsum AS PS JOIN LOCA05.DBO.TBPOSTRANSACT AS P ON PS.ITEMCODE=P.ITEMCODE
AND PS.REFCODE=P.REFCODE AND PS.DESCRIP=P.DESCRIP AND PS.IDI1=P.IDI1 AND PS.IDISCOUNT1=P.IDISCOUNT1 
AND P.IDIS1=PS.IDIS1 AND P.LOCA=PS.LOCA  AND P.ZNO=PS.ZNO  AND P.ROWNO=PS.ROWNO
AND P.RECEIPT=PS.RECEIPT 
WHERE P.PROMID='24' ORDER BY PS.IDX

BEGIN TRAN
UPDATE PS SET PS.PROMID=P.PROMID FROM LOCA05.DBO.TBPOSTRANSACT AS P JOIN tbpostransactsum AS PS ON P.ITEMCODE=PS.ITEMCODE
AND P.REFCODE=PS.REFCODE AND P.DESCRIP=PS.DESCRIP AND P.IDI1=PS.IDI1 AND P.IDISCOUNT1=PS.IDISCOUNT1
AND P.IDIS1=PS.IDIS1 AND P.LOCA=PS.LOCA AND P.ZNO=PS.ZNO AND P.RECEIPT=PS.RECEIPT AND P.ROWNO=PS.ROWNO
WHERE P.PROMID='24'
COMMIT
ROLLBACK

 ------18----------
 select * from tbpostransactsum where loca='02' and itemcode='DISCOUNT'
 and descrip='BIRTH DAY WISHES 20%' and SDis='20%' and iid='006'
 and unitno='1'

 update tbpostransactsum set promid='18' where loca='02' and itemcode='DISCOUNT'
 and descrip='BIRTH DAY WISHES 20%' and SDis='20%' and iid='006'
 and unitno='1'